<a href="https://colab.research.google.com/github/SiddhantMS/Statistics/blob/main/sudeep_bhargav_numpy_day1_18_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DAY 1**\

**DAY 1**\

In [ ]:
import numpy as np

In [ ]:
x1 = [4,4,6,9,6,0]

str(x1)
#[4, 4, 6, 9, 6, 0]

type(x1)
#list

a1 = np.array(x1)
type(a1)
#numpy.ndarray

x2 = [3,4,6,7.,1,7]

a2 = np.array([x1,x2])    # adding two array will give 2d array

a2
#array([[4., 4., 6., 9., 6., 0.],
#       [3., 4., 6., 7., 1., 7.]])      gives 2d arrar



In [ ]:
x1 = list(range(11))

x1  #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

a1 = np.array(x1)

a1     #array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

a1 = np.arange(3,14)
a1     #array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

a1 = np.arange(5,26,3)
a1       #array([ 5,  8, 11, 14, 17, 20, 23])
a1 = np.arange(5,27,3)
a1       #array([ 5,  8, 11, 14, 17, 20, 23, 26])
#see difference of output

a1 = np.arange(24,5,-2)
a1 #array([24, 22, 20, 18, 16, 14, 12, 10,  8,  6])
a1 = np.arange(24,5,-1)
a1    #array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8, 7,  6])

a1 = np.arange(20,2,1.5)  # the 1.5 is number of values we cannot give in desimal not difference between that
a1

x1 = np.linspace(10,30,7) # including 10 and 30 this command generate of array which has 7 numbers and these are equal
x1   #array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,       26.66666667, 30.        ])

x1 = np.linspace(10,30,7,endpoint=False)
x1     #array([10.        , 12.85714286, 15.71428571, 18.57142857, 21.42857143, 24.28571429, 27.14285714])

a1 = np.array([4,5,7,8,9,2])
np.append(a1,3) #array([4, 5, 7, 8, 9, 2, 3])
a1   #array([4, 5, 7, 8, 9, 2])
a1 = np.append(a1,3)
a1  #array([4, 5, 7, 8, 9, 2, 3])
#a1 = np.append(a1,4,5) # cnant do
a1 = np.insert(a1,4,5)

a2 = np.array([2,9,8])

a3 = np.concatenate((a1,a2))
a3   #array([4, 5, 7, 8, 9, 2, 3, 2, 9, 8])

a4 = np.concat((a1,a2))
a4    #array([4, 5, 7, 8, 9, 2, 3, 2, 9, 8])

# basic -

a1 = np.array([3,7,1,9,2,0,5,1])
len(a1) #8

a2 = a1.reshape(4,2) #giving array of 4 rows and 2 colns (r,c)
a2
'''
array([[3, 7],
       [1, 9],
       [2, 0],
       [5, 1]])
'''

a3 = a1.reshape(-1,1)
a3
'''
array([[3],
       [7],
       [1],
       [9],
       [2],
       [0],
       [5],
       [1]])
'''

a4 = a1.reshape(-1,2)
# -1 is for rows are free and i only wnat to reshape colons like 2
a4

a4 = a1.reshape(2,-1)
a4

a4[1]  #array([2, 0, 5, 1])
a4[1,:] # why this option if i want to get colum then i will help #array([2, 0, 5, 1])

a4[:,1] # here it is helping to get coln only  #array([7, 0])
#a4([2,3],)

In [ ]:
newcol = np.array([3,4,5,6])

newcol = newcol.reshape(-1,1)

newcol
'''
array([[3],
       [4],
       [5],
       [6]]
'''

a5 = np.hstack([a2,newcol])
a5

newrow = np.array([5,5,5])
a6 = np.vstack([a5,newrow])
a6


#want to insert choice of row and coln

#a7 = np.insert(array which insertion should happen , index of array, what are values)
a6 = np.insert(a6,3,[10,10,10],axis = 0)
a6
a7 = np.insert(a6,3,[11,11,11],axis = 0)
a7

# for insert new colon
a8 = np.insert(a6,2,[0,0,0,0,0,0],axis=1)
a8

# t0 delete rows and colns

a9 = np.delete(a8,(1,3),axis =0)
a9
a10 = np.delete(a8,(1,3),axis = 1)
a10

In [ ]:
#      brodcasting
# to repeat same operation across all the values
#this is not possible wiht list


a1 = np.array([4,7,6,8,9])
a2 = np.array([4,2,7,6,3])

a1 + 5  # this is brodcasting  o/p array([ 9, 12, 11, 13, 14])
2*a1+5  # array([13, 19, 17, 21, 23])

a1+a2  # in list it will concanate but here item to item operation willl happen
#   array([ 8,  9, 13, 14, 12])

a3 = np.array([2,3])
#a1+a3 #ValueError: operands could not be broadcast together with shapes (5,) (2,)
# here recycling of operation will not happent like R


In [ ]:
a1 = np.array([3,5,7,8,1,6,9,2,4,6,7,1])
len(a1)

a2 = a1.reshape(3,4)
a2
'''
array([[3, 5, 7, 8],
       [1, 6, 9, 2],
       [4, 6, 7, 1]])
'''
a3 = np.array([2,4,6,8])

a2+a3
'''
array([[ 5,  9, 13, 16],
       [ 3, 10, 15, 10],
       [ 6, 10, 13,  9]])
'''

a4 = np.array([3,4,5])
a4 = a4.reshape(-1,1)
a4
'''
array([[3],
       [4],
       [5]])
'''

a2+a4
'''
array([[ 6,  8, 10, 11],
       [ 5, 10, 13,  6],
       [ 9, 11, 12,  6]])
'''

a1 #array([3, 5, 7, 8, 1, 6, 9, 2, 4, 6, 7, 1])
# i want to delete 3,5 8 in single command
a1[[3,5,8]]  #array([8, 6, 4])

a1[3] #np.int64(8)

#a1[[lambda x : x>4,a1]]

'''
que1: where are the values which are greter than 4
que2 : how many values are greater than 4
que 3 : what are the values
'''

que1 = np.where(a1>4)
que1  #(array([ 1,  2,  3,  5,  6,  9, 10]),)
#      input to the np.where command is a condition that neads to be checked
# output of the np.where comand are the index/ indesies where the condithion is found be true


#que2:que2 : how many values are greater than 4

#len(que1[0])   #7

#(a1>4).sum()  #np.int64(7)

#que 3 : what are the values
a1[[np.where(a1>4)]]  #array([[[5, 7, 8, 6, 9, 6, 7]]])
a1[que1[0]]

array([5, 7, 8, 6, 9, 6, 7])

x1 = (np.arange(48)).reshape(6,8)   # creates a 2d array of 6 rows and 8 columns
x2 = np.resize(x1,(12,4))   #  resizes the array x1 which was having 6 rows and 8 cols to an array with 12 rows and 4 cols

x3 = np.split(x2,[1,3,5])	# splits the array at the indices mentioned. The resultant arrays  are different items in a list. So basically we get list of arrays. By defaults axis=0 so splitting is done horizontally
x4 = np.split(x1,[2,3,5], axis=1)    # splitting happens vertically


b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
c = sorted(b)          #sorts the array in increasing order
c = sorted(b)[::-1]    # sorts the array in the decreasing order
np.sort(b)     # also PRINTS the array in the increasing order, original array is unchanged

b=b.reshape(3,4)   # reshapes b as a 2d array with 3 rows and 4 columns
np.sort(b,axis=0)   # row wise values will be changed. Column values are only rearranged
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

In [ ]:
x1 = (np.arange(48)).reshape(6,8)
x1
'''
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])
'''

x2 = np.resize(x1,(12,4))
x2
'''
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])
'''


[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [ ]:
x3 = np.split(x2,[1,3,5])
x3

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]])]

In [ ]:
x4 = np.split(x1,[2,3,5], axis=1)
x4

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25],
        [32, 33],
        [40, 41]]),
 array([[ 2],
        [10],
        [18],
        [26],
        [34],
        [42]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28],
        [35, 36],
        [43, 44]]),
 array([[ 5,  6,  7],
        [13, 14, 15],
        [21, 22, 23],
        [29, 30, 31],
        [37, 38, 39],
        [45, 46, 47]])]

In [ ]:
b=np.array([2,4,1,7,6,5,9,8,2,3,1,5])
b
c = sorted(b) #sorts the array in increasing order
c


[np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [ ]:
c = sorted(b)[::-1] # sorts the array in the decreasing
c

[np.int64(9),
 np.int64(8),
 np.int64(7),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(4),
 np.int64(3),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(1)]

In [ ]:
np.sort(b)

array([1, 1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [ ]:
b=b.reshape(3,4)
b

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [ ]:
np.sort(b,axis=0)

array([[2, 3, 1, 5],
       [2, 4, 1, 7],
       [6, 5, 9, 8]])

In [ ]:
np.sort(b,axis=1)   # column wise values will be changed. Row values are only rearranged

array([[1, 2, 4, 7],
       [5, 6, 8, 9],
       [1, 2, 3, 5]])

In [ ]:
b =b.reshape(3,4)
b

array([[2, 4, 1, 7],
       [6, 5, 9, 8],
       [2, 3, 1, 5]])

In [ ]:
que1 = np.where(b>=4)
que1

(array([0, 0, 1, 1, 1, 1, 2]), array([1, 3, 0, 1, 2, 3, 3]))

In [ ]:
type(que1)
(b>=4).sum()

np.int64(7)

In [ ]:
# repeat comands
r1 = [5,8,0]
r2 = r1*3
r2

[5, 8, 0, 5, 8, 0, 5, 8, 0]

In [ ]:
r3 = np.repeat(r1,3)
r3

array([5, 5, 5, 8, 8, 8, 0, 0, 0])

In [ ]:
r4 = np.repeat(r1,[4,6,3])
r4

array([5, 5, 5, 5, 8, 8, 8, 8, 8, 8, 0, 0, 0])

In [ ]:
a1 = np.array([4,7,6,8,2,4,1,8])

np.sort(a1)

np.argsort(a1) # gives the index of lowest to higest

array([6, 4, 0, 5, 2, 1, 3, 7])

In [ ]:
a1 = np.array([6,5,4,8,7,6,2,2,5,7,1,8,1])
len(a1)

np.unique(a1) # will give unique element in array array([1, 2, 4, 5, 6, 7, 8])

np.unique(a1, return_counts = True) #giveing the no of occurance the element is coming the first array will giving element and second one is no of times it is coming
#(array([1, 2, 4, 5, 6, 7, 8]), array([2, 2, 1, 2, 2, 2, 2]))

np.unique(a1,return_index= True) # this will give  first occuring position of index the element are coming
#(array([1, 2, 4, 5, 6, 7, 8]), array([10,  6,  2,  1,  0,  4,  3]))
np.unique(a1,return_inverse= True)

(array([1, 2, 4, 5, 6, 7, 8]), array([4, 3, 2, 6, 5, 4, 1, 1, 3, 5, 0, 6, 0]))

## **DAY 2**\


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# when in probablity we have AND comes then multiply
# when or comes in parobablity should be addition
#union - or
# intersection - and


In [ ]:
a1 = np.array([3,6,4,6,5,8,7])
a2 = np.array([3,5,7,6,5,4,9])

In [ ]:
np.intersect1d(a1,a2) #giving the intersection of two arrays

array([3, 4, 5, 6, 7])

In [ ]:
np.union1d(a1,a2)  #giveing the uniion of two arrays

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.setdiff1d(a1,a2) # unique to a1  only in a1 not in a2
np.setdiff1d(a2,a1) #unique to a2 only

array([9])

In [ ]:
np.setxor1d(a1,a2) #all the unique elements which is either in a1 or in a2
# union of unique elements
#union - intersection is setxor

array([8, 9])

In [ ]:
np.isin(a1,a2) # take element from a1 and check does a2 has that element and gives in bollen
# isin() gives a logical array

array([ True,  True,  True,  True,  True, False,  True])

In [ ]:
a1 = np.array([2,3,4,1,0,5])
a1 = np.reshape(a1,[2,3])
a1

array([[2, 3, 4],
       [1, 0, 5]])

In [ ]:
a2 = np.array([1,0,2,5,4,3])
a2 = np.reshape(a2,[3,2])
a2

array([[1, 0],
       [2, 5],
       [4, 3]])

In [ ]:
a1*a2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
#vertices multiplication
# dot product
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])
np.dot(x1,x2)

np.int64(-4)

In [ ]:
from numpy import linalg

x3 = np.array([[1,2,3],[0,1,2],[1,1,0]])

In [ ]:
np.linalg.det(x3) #will give determainat of a matrix


np.float64(-1.0)

In [ ]:
from numpy import random
np.random.rand(10)  # 10 random no between 0 and 1

array([0.26164322, 0.18135098, 0.19947332, 0.9528168 , 0.10737426,
       0.86671796, 0.94434289, 0.94694475, 0.07466227, 0.38870015])

In [ ]:
np.random.randint(5,50)  # 1 random no betn 5 and 50
np.random.randint(5,50,15) # 15 random no betn 5 and 50

array([31, 46, 32, 18, 15, 16, 26, 24, 35, 34, 28, 49, 18, 23, 17])